[package]
name = "file-mst"
version = "0.1.0"
edition = "2024"

[dependencies]
blake3 = "1.8"
bytes = "1.11"
postcard = "1.1"
rkyv = { version = "0.8.14" }
serde = { version = "1.0", features = ["derive"] }
tempfile = "3.24"

[dev-dependencies]
hex = "0.4.3"
rand = "0.9.2"
